export const dummyFeeds = [
    {
      id: 1,
      user: {
        userId: 1,
        name: "John Doe",
        avatar: "https://i.pravatar.cc/150?img=1",
      },
      timestamp: "5 mins ago",
      content: "Just joined QuickExpert! Excited to connect and learn from experts!",
      image: null,
      likes: 12,
      comments: 3,
    },
    {
      id: 2,
      user: {
        userId: 2,
        name: "Jane Smith",
        avatar: "https://i.pravatar.cc/150?img=5",
      },
      timestamp: "30 mins ago",
      content: "Check out my new UI/UX design portfolio. Feedback is welcome!",
      image: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80",
      likes: 45,
      comments: 8,
    },
    {
      id: 3,
      user: {
        userId: 3,
        name: "Mike Lee",
        avatar: "https://i.pravatar.cc/150?img=8",
      },
      timestamp: "1 hour ago",
      content: "Excited to announce I just landed a remote job as a backend developer!",
      image: null,
      likes: 78,
      comments: 15,
    },
    {
      id: 4,
      user: {
        userId: 4,
        name: "Sarah Johnson",
        avatar: "https://i.pravatar.cc/150?img=11",
      },
      timestamp: "2 hours ago",
      content: "Just deployed my first machine learning model to production! #AI #ML",
      image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=600&q=80",
      likes: 92,
      comments: 24,
    },
    {
      id: 5,
      user: {
        userId: 5,
        name: "David Chen",
        avatar: "https://i.pravatar.cc/150?img=15",
      },
      timestamp: "3 hours ago",
      content: "Working on a new blockchain project. Can't wait to share more details soon!",
      image: "https://images.unsplash.com/photo-1639762681057-408e52192e55?auto=format&fit=crop&w=600&q=80",
      likes: 56,
      comments: 12,
    },
    {
      id: 6,
      user: {
        userId: 6,
        name: "Emma Wilson",
        avatar: "https://i.pravatar.cc/150?img=20",
      },
      timestamp: "5 hours ago",
      content: "Completed my React certification today! What should I learn next?",
      image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=600&q=80",
      likes: 103,
      comments: 31,
    },
    {
      id: 7,
      user: {
        userId: 7,
        name: "Alex Rodriguez",
        avatar: "https://i.pravatar.cc/150?img=25",
      },
      timestamp: "7 hours ago",
      content: "My team just launched our new mobile app. Check it out and let me know what you think!",
      image: "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?auto=format&fit=crop&w=600&q=80",
      likes: 87,
      comments: 19,
    },
    {
      id: 8,
      user: {
        userId: 8,
        name: "Priya Patel",
        avatar: "https://i.pravatar.cc/150?img=30",
      },
      timestamp: "9 hours ago",
      content: "Giving a talk about cybersecurity best practices at the TechConf next week!",
      image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80",
      likes: 64,
      comments: 14,
    },
    {
      id: 9,
      user: {
        userId: 9,
        name: "Marcus Wong",
        avatar: "https://i.pravatar.cc/150?img=35",
      },
      timestamp: "12 hours ago",
      content: "Just open-sourced my new data visualization library. Contributions welcome!",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
      likes: 112,
      comments: 27,
    },
    {
      id: 10,
      user: {
        userId: 10,
        name: "Olivia Kim",
        avatar: "https://i.pravatar.cc/150?img=40",
      },
      timestamp: "1 day ago",
      content: "Our startup just secured Series A funding! Exciting times ahead.",
      image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80",
      likes: 156,
      comments: 42,
    },
    {
      id: 11,
      user: {
        userId: 11,
        name: "Thomas Baker",
        avatar: "https://i.pravatar.cc/150?img=45",
      },
      timestamp: "1 day ago",
      content: "Teaching myself Python for data science. Any recommended resources?",
      image: "https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&w=600&q=80",
      likes: 73,
      comments: 23,
    },
    {
      id: 12,
      user: {
        userId: 12,
        name: "Nadia Ahmed",
        avatar: "https://i.pravatar.cc/150?img=50",
      },
      timestamp: "2 days ago",
      content: "Just migrated our infrastructure to microservices. The performance improvement is incredible!",
      image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80",
      likes: 94,
      comments: 18,
    },
    {
      id: 13,
      user: {
        userId: 13,
        name: "Carlos Mendez",
        avatar: "https://i.pravatar.cc/150?img=55",
      },
      timestamp: "2 days ago",
      content: "Looking for beta testers for our new productivity app. DM me if interested!",
      image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=600&q=80",
      likes: 68,
      comments: 15,
    },
    {
      id: 14,
      user: {
        userId: 14,
        name: "Sophie Martin",
        avatar: "https://i.pravatar.cc/150?img=60",
      },
      timestamp: "3 days ago",
      content: "Our AI research paper got accepted to NeurIPS! So proud of my team.",
      image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80",
      likes: 210,
      comments: 53,
    },
    {
      id: 15,
      user: {
        userId: 15,
        name: "Kwame Osei",
        avatar: "https://i.pravatar.cc/150?img=65",
      },
      timestamp: "3 days ago",
      content: "Built an automated testing framework that reduced our QA time by 70%.",
      image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=600&q=80",
      likes: 127,
      comments: 29,
    }
  ];

